#!/bin/sh
#; -*- mode: Makefile;-*-
#the next line restarts using\
exec make --trace --warn-undefined-variables -Rf "$0"  ${1+"$@"} 
# =========================================================
# Copyright 2015
#
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with iRAP.  If not, see <http://www.gnu.org/licenses/>.
#
#
# =========================================================
###############################################################
# disable deletion of temporary files
.SECONDARY: 
.ONESHELL:

SHELL=bash
##################
# Setup some paths
# path to script


# Requires make 4.1 or above
VERSION_OK=$(shell if [ `make --version|head -n 1 | cut -f3 -d\ ` \< 4.1 ]; then echo 0; else echo 1; fi )
ifeq ($(VERSION_OK),0)
 $(error make version needs to be 4.1 or above)
endif

script_path!=dirname "`which eqtl_pipeline`"
################################################################################
# Auxiliary functions
################################################################################

# Information messages
define p_info=
$(info $(shell date "+%H:%M:%S %d/%m/%Y * ") $(1))
endef

# Error messages
define p_error=
$(info $(shell date "+%H:%M:%S %d/%m/%Y") * ERROR: $(1)) && $(error Fatal error)
endef

# complain if a file does not exist and exit
file_exists=$(if  $(realpath $(1)),,$(call p_error,$(1) not found))

#  check if a variable  $(1) is defined - return the variable name if it is defined or empty otherwise
is_defined=$(if $(subst undefined,,$(origin $(1))),$(1),)


################################################################################
# Variables
################################################################################

#Version and license info
pname=eqtlXXXXX
version=0.0.1
contact="Add contact"
license=This pipeline is distributed  under the terms of the GNU General Public License 3


################################################################################
# Default values
################################################################################
# max. memory (in MB)
def_max_mem=6000

def_max_threads=1

################################################################################
# go...

$(info *****************************************************)
$(info * $(pname) $(version))
$(info * $(contact))
$(info * $(license))
$(info *)
$(info * Initializing...)


###############################################
# Load configuration (mandatory)
# use a configuration file?
ifdef conf
 $(call file_exists,$(conf))
 $(info * Trying to load configuration file $(conf)...)
 include $(conf)
 $(info * Configuration loaded.)
else
 $(call p_error,Configuration file missing)
endif

###############################################################
# Check and validate the parameters values

$(info * )
$(info * Required Parameters:)

#***********************
# Name of the experiment
ifndef name
 $(call p_error, missing argument name!)
else
 $(info *	name=$(name))
endif


# expr_matrix (TSV File)
ifndef expr_matrix
 $(call p_error, missing argument expr_matrix!)
else
 $(info *	expr_matrix=$(expr_matrix))
endif
$(call file_exists,$(expr_matrix))

# two columns
# 1st column: DNA
# 2st column: RNA
ifndef dna_rna_mapfile
 $(call p_error, missing argument dna_rna_mapfile)
else
 $(info *	name=$(dna_rna_mapfile))
endif
$(call file_exists,$(dna_rna_mapfile))



#************************
# ?
ifndef vcf_toplevel_dir
$(call p_error,vcf_toplevel_dir not defined)
endif
$(info *	vcf_toplevel_dir=$(vcf_toplevel_dir))

ifndef vcfs
 $(call p_error,missing argument vcfs)
endif
$(info *	vcfs=$(vcfs))
#$(call file_exists,$(vcfs))
$(foreach l,$(vcfs),$(call file_exists,$(vcf_toplevel_dir)/$(l)))

#
ifndef cov_matrix
cov_matrix=none
$(call p_error,cov_matrix not defined)
endif
$(call file_exists,$(cov_matrix))
$(info *	cov_matrix=$(cov_matrix))
# eqtl_pipeline vcfs=`ls mydir/*.vcf.gz`


#********* 
# GTF file?
ifndef gtf_file
 $(error gtf_file not defined)
endif
$(info *       gtf_file  = $(gtf_file))
$(call file_exists,$(gtf_file))

# vcfs??

chromosomes?=1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y MT


# 2 remove
LIMIX_BINARY=/panfs/nobackup/production/sds-pawg/ccalabre/germlinevcf/limix_pmbio/build/release.linux2/interfaces/python/bin/


#####################
# Other Optional parameters
#####################
$(info * )
$(info * Optional Parameters:)


#
def_vars=minGQ minRD  min_expr min_perc_samples expr_transform hidden_k max_missing mac peer_iterations snr_threshold max_missing vcf_filter_cmd
peer_iterations?=100
minGQ?=50
minRD?=20
# signal-to-noise ration threshold
snr_threshold?=75
# vcf_filter="TP > 0.95 ....."

vcf_filter_cmd=annai_filter_vcf.sh

min_expr?=1
min_perc_samples?=0.5
#possible values: gaussian log none
expr_transform?=none
hidden_k?=10
max_missing?=0.8

mac?=20

$(foreach v,$(def_vars),$(info * 	$(v)=$($(v))))

#********
# Threads
#********
ifndef max_threads
 max_threads=$(def_max_threads)
endif
$(info *	max_threads=$(max_threads))


##############################
# expression correction method
SUPPORTED_CORR_METHODS=peer panama
ifndef corr_method
corr_method=none
endif

#corr_method expr_corr_method?
ifeq (,$(filter $(corr_method),$(SUPPORTED_CORR_METHODS) none))
$(error corr_method value $(corr_method) not supported)
endif

ifeq ($(corr_method),peer) 
$(info peer!!!)
else 
$(info *	corr_method=$(corr_method))
endif

#
# mem in MB
ifndef max_mem
max_mem=$(def_max_mem)
endif
# max memory in GB
max_mem_gb:=$(shell expr $(max_mem) \/ 1000)

# set memory (in bytes) to 65% of the max. memory available
#ifndef SAMTOOLS_SORT_MEM
# SAMTOOLS_SORT_MEM:=`expr $(max_mem) \* 1000000 \* 65 \/ 100`
#endif


# samtools 1.x
ifndef SAMTOOLS_SORT_MEM
 SAMTOOLS_SORT_MEM:=$(shell bash -c "expr $(max_mem_gb) \* 75 \/ 100")G
endif

#
TARGETS1=
TARGETS2=
TARGETS3=
TARGETS4=

#
# ${name}
#   |+-------------dna_[dna_filter_options_md5]
#   |+-------------rna_[rna_filter_options_md5]
#   |+-------------peer_[step3_md5]/
#   |+-------------panama_[step3_md5]/
#   |+-------------none_[step3_md5]/
#	{1,2,...}
#       1.hd5



# HASH
step1_hash!=echo $(minGQ) $(minRD) $(max_missing) $(mac) $(vcf_filter_cmd) |md5sum|cut -f1 -d' ' 
step2_hash!=echo $(min_expr) $(min_perc_samples) $(expr_transform) $(hidden_k)|md5sum|cut -f1 -d' '


ifeq ($(corr_method),peer)
step3_hash!=echo $(step1_hash) $(step2_hash) $(peer_iterations) $(hidden_k) $(expr_transform)|md5sum|cut -f1 -d' '
else
ifeq ($(corr_method),panama)
step3_hash!=echo $(step1_hash) $(step2_hash)  $(hidden_k) $(snr_threshold) $(expr_transform)|md5sum|cut -f1 -d' '
else
step3_hash!=echo $(step1_hash) $(step2_hash)|md5sum|cut -f1 -d' '
endif
endif

step1_dir:=$(name)/dna_$(step1_hash)
step2_dir:=$(name)/rna_$(step2_hash)
step3_dir:=$(name)/$(corr_method)_$(step3_hash)

$(info step1_dir=$(step1_dir))

# create the folders
$(shell mkdir -p $(step1_dir) $(step2_dir) $(step3_dir))

###############
# names of files
cov_hdf5=$(name)/$(notdir $(basename $(cov_matrix))).hdf5
gtf_eqtl_tsv=$(subst .gtf,.gtf.eqtl.tsv,$(subst .gz,,$(gtf_file)))
expr_matrix_filename=$(notdir $(basename $(expr_matrix)))
kpop_file=$(step1_dir)/Kpop.hdf5
samples_hdf5=$(step1_dir)/samples.hdf5

################################################################################
# Make stuff
phony_targets=
silent_targets= 

empty:=
space:=$(empty) $(empty)#
################################################################################
# AUXILIARY FUNCTIONS
################################################################################

################################################################################
# Default target
all: step1 step2 step3	step4


################################################################################
#
################################################################################
# Generic file extension rules

# 
%.vcf.gz.tbi: %.vcf.gz
	tabix -p vcf $< || ( rm -f $@ && exit 1)

%.vcf.tbi: %.vcf
	tabix -p vcf $<  || ( rm -f $@ && exit 1)

%.gtf: %.gtf.gz
	gunzip -c $< > $@.tmp && mv $@.tmp $@
# 
%.gtf.eqtl.tsv: %.gtf
	get_annotation.sh $<  $@.tmp && mv $@.tmp $@


$(cov_hdf5): $(cov_matrix)
	get_covariates.py $< $@.tmp && mv $@.tmp $@

#################################################################################
#
# Step0,1 and 2 may be executed independently

step0: $(name)/$(expr_matrix_filename).matched.tsv $(cov_hdf5)

$(name)/$(expr_matrix_filename).matched.tsv: $(dna_rna_mapfile) $(expr_matrix)
	pheno_preprocessing.py $^ $@.tmp && mv $@.tmp $@


#################################################################################
# DNA

step1: $(step1_dir)/complete
# STEP1
step1_a: tbi_files
step1_b: fix_vcf_headers
step1_c: filter_vcfs
step1_d: $(kpop_file) $(step1_dir)/data_consistent


# required: .tbi for each vcf
TBI_FILES=$(foreach l,$(vcfs),$(l).tbi)
tbi_files: $(TBI_FILES)

TARGETS1+=$(TBI_FILES)


# fix spaces in header?
FIXEDHEADER_VCFS=$(foreach l,$(vcfs),$(subst .vcf.gz,.fixedheader.vcf.gz,$(l)))
fix_vcf_headers: $(FIXEDHEADER_VCFS) 
	echo $(FIXEDHEADER_VCFS)

$(name)/vcf/%.fixedheader.vcf.gz: $(vcf_toplevel_dir)/%.vcf.gz
	mkdir -p $(@D) && fix_vcf_header.sh $< $@.tmp && mv $@.tmp $@


# Rules to process each chr
# chr=$(1) 
define make-rules-for-chr=

$(shell mkdir -p $(step1_dir)/$(1))

$(step1_dir)/$(1)/chr$(1).merged.vcf.gz: $$(foreach l,$(vcfs),$(step1_dir)/$(1)/$$(subst .vcf.gz,.filter.vcf.gz,$$(l))) $$(foreach l,$(vcfs),$(step1_dir)/$(1)/$$(subst .vcf.gz,.filter.vcf.gz.tbi,$$(l)))
	$$(file > $$@.lst,$$(foreach l,$(vcfs),$(step1_dir)/$(1)/$$(subst .vcf.gz,.filter.vcf.gz,$$(l))))  \
	sed -i "s/^ //" $$@.lst && \
	bcftools merge -l $$@.lst --output-type z > $$@.tmp && \
	rm -f $$@.lst && \
	mv $$@.tmp $$@

$(step1_dir)/$(1)/%.filter.vcf.gz: $(name)/vcf/%.fixedheader.vcf.gz
	$(vcf_filter_cmd) -i $$< -o $$@.tmp -c $(1) -g $(minGQ) -d $(minRD)  && mv $$@.tmp $$@

##select MAC >=5, allow max missing sites in 20 percent of samples
$(step1_dir)/plink/$(1)/chr$(1).merged.vcf.gz.plink: $(step1_dir)/$(1)/chr$(1).merged.vcf.gz
	mkdir -p $$(@D) &&
	vcftools --gzvcf $$< --max-missing $(max_missing) --mac $(mac) --recode --recode-INFO-all --temp $$(@D) --stdout | \
        vcftools --vcf - --plink --out $$@.tmp && mv $$@.tmp.ped $$@.ped &&  mv $$@.tmp.map $$@.map && touch $$@


$(step1_dir)/plink/$(1)/plink_chr$(1).done: $(step1_dir)/plink/$(1)/chr$(1).merged.vcf.gz.plink
	plink --file $$< --make-bed --noweb --out $$(subst .done,,$$@) && touch $$@

##convert genotypes into hdf5 file using limix binaries
##echo 'convert plink files into hdf5 files using limix binaries'
$(step1_dir)/plink/$(1)/chr$(1).hdf5: $(step1_dir)/plink/$(1)/plink_chr$(1).done 
	python $(LIMIX_BINARY)/limix_converter --outfile=$$@.tmp --plink=$$(subst .done,,$$<) && \
	geno_preprocessing.py $$@.tmp && \
	mv $$@.tmp $$@

endef

# Generate the rules per chr
$(foreach chr,$(chromosomes),$(eval $(call make-rules-for-chr,$(chr))))

# todo add samples.hdf5???
#build_Kpop.py outfile hdf5files....
#build_Kpop.py kop.hdf5.tmp samples.hdf5 ...chr1.hdf5 ...chr2.hdf5 ...chr3.hdf5
$(kpop_file) $(samples_hdf5): $(foreach chr,$(chromosomes),$(step1_dir)/plink/$(chr)/chr$(chr).hdf5)
	build_Kpop.py $@.tmp $(samples_hdf5).tmp $^ && \
	mv $(samples_hdf5).tmp $(samples_hdf5) &&\
	mv $@.tmp $@

TARGETS2+=$(foreach chr,$(chromosomes),$(step1_dir)/plink/$(chr)/chr$(chr).hdf5)
TARGETS3+=$(step1_dir)/data_consistent


$(step1_dir)/data_consistent: $(dna_rna_mapfile) $(kpop_file)
#	check_consistency.py $(dna_rna_mapfile) $(kpop_file) $(expr_matrix) && touch $(step1_dir)/data_consistent
	check_consistency.py $(dna_rna_mapfile) $(samples_hdf5) && touch $(step1_dir)/data_consistent

$(step1_dir)/complete: $(step1_dir)/data_consistent $(kpop_file)
	touch $@

################################################################################
# RNA

#
TARGETS1+=step2


step2: $(step2_dir)/complete


$(step2_dir)/$(expr_matrix_filename).limix.hdf5: $(name)/$(expr_matrix_filename).matched.tsv $(gtf_eqtl_tsv)
	$(LIMIX_BINARY)/limix_converter --outfile=$@.tmp --csv=$< && \
	hdf_annotation.py $(gtf_eqtl_tsv) $@.tmp && \
	mv $@.tmp $@	


$(step2_dir)/$(expr_matrix_filename).filtered.hdf5: $(step2_dir)/$(expr_matrix_filename).limix.hdf5  $(samples_hdf5) $(cov_hdf5)
	cp $< $@.tmp && \
	filtering_pheno.py $< $(min_expr) $(min_perc_samples) $(expr_transform) $@.tmp && \
	sort_ids.py $@.tmp $(cov_hdf5) $(samples_hdf5) &&\
	mv $@.tmp $@

$(step2_dir)/complete: $(step2_dir)/$(expr_matrix_filename).filtered.hdf5 $(name)/$(expr_matrix_filename).matched.tsv
	touch $@


######################################################################
# step3
step3: $(step3_dir)/complete

TARGETS3+= $(step3_dir)/$(corr_method)/$(corr_method).hdf5
# kpop - ktot
$(step3_dir)/panama/panama.hdf5: $(kpop_file) $(step2_dir)/$(expr_matrix_filename).filtered.hdf5
	mkdir -p $(@D) && \
	runpanama.py  $(kpop_file) $(step2_dir)/$(expr_matrix_filename).filtered.hdf5 $(hidden_k) $(snr_threshold) $@.tmp &&\
	mv $@.tmp  $@

$(step3_dir)/peer/peer.hdf5: $(step2_dir)/$(expr_matrix_filename).filtered.hdf5
	mkdir -p $(@D) && \
	runpeer.py $<  $(hidden_k) $(peer_iterations) $@.tmp && \
	mv $@.tmp  $@

$(step3_dir)/none/none.hdf5: $(kpop_file)
	mkdir -p $(@D) && \
	cp $< $@.tmp && \
	mv $@.tmp  $@

$(step3_dir)/complete: $(step1_dir)/complete $(step2_dir)/complete $(step3_dir)/$(corr_method)/$(corr_method).hdf5

################################################################################
step4: $(step1_dir)/complete $(step2_dir)/complete $(step3_dir)/complete $(step3_dir)/step4.complete
# 
#
n_folds=1000

#: $(step1_dir)/complete $(step2_dir)/complete $(step2_dir)/$(expr_matrix_filename).filtered.hdf5 $(step3_dir)/$(corr_method)/$(corr_method).hdf5 $(kpop_file) 
#	cis_eqtl_run.py $(chr) $(step1_dir) $(step2_dir)/$(expr_matrix_filename).filtered.hdf5  $(corr_method) $(step3_dir)/$(corr_method)/$(corr_method).hdf5 $(kpop_file)y $(expr_transform) $(n_folds)
# 
#

# foreach chr
#   foreach fold_j in 1...nfolds
#     cis_eqtl.py $(chr) $(fold_j) $(nfolds) $(outname) -> chr/$nfolds_fold_j.hdf5
All_CisQTL_JOBS=$(foreach j,$(shell seq $(n_folds)),$(foreach chr,$(chromosomes), $(step3_dir)/$(chr)/$(n_folds)_$(j).hdf5))

# $(1)=chr
define CisQTL_JOBS_chr=
$(foreach j,$(shell seq $(n_folds)), $(step3_dir)/$(1)/$(n_folds)_$(j).hdf5)
endef

#$(info $(All_CisQTL_JOBS))
TARGETS4+=$(All_CisQTL_JOBS)

# $(1) = chr
define make-cisqtl-rule-chr=
$(step3_dir)/$(1)/$(n_folds)_%.hdf5: $(step1_dir)/plink/$(1)/chr$(1).hdf5 $(step2_dir)/$(expr_matrix_filename).filtered.hdf5  $(kpop_file) $(step3_dir)/$(corr_method)/$(corr_method).hdf5 $(cov_hdf5)
	mkdir -p $$(@D) && eqtl_cis.py $(step1_dir)/plink/$(1)/chr$(1).hdf5   $(step2_dir)/$(expr_matrix_filename).filtered.hdf5  $(corr_method)  $(step3_dir)/$(corr_method)/$(corr_method).hdf5  $(kpop_file) $(cov_hdf5) $(n_folds) $$* $$@.tmp && mv $$@.tmp $$@

# 
$(step3_dir)/$(1)/summary.hdf5: $(call CisQTL_JOBS_chr,$(1))  $(cov_hdf5) $(step2_dir)/$(expr_matrix_filename).filtered.hdf5 $(step3_dir)/$(corr_method)/$(corr_method).hdf5
	$(file >$$@.lst.txt,$$^) \
	eqtl_summary.py $(step1_dir)/plink/$(1)/chr$(1).hdf5  $(step2_dir)/$(expr_matrix_filename).filtered.hdf5  $(corr_method) $(step3_dir)/$(corr_method)/$(corr_method).hdf5  $(kpop_file) $(cov_hdf5)  $(n_folds) $$@.lst.txt  $$@.tmp && \
	rm -f $$@.lst.txt && \
	mv $$@.tmp $$@

$(step3_dir)/$(1).hdf5: $(step3_dir)/$(1)/summary.hdf5
	get_final_res.py $(step3_dir)/$(1)/summary.hdf5 $$@.tmp && mv $$@.tmp $$@

endef

$(foreach chr,$(chromosomes),$(eval $(call make-cisqtl-rule-chr,$(chr))))


$(step3_dir)/step4.complete:  $(step3_dir)/complete $(foreach chr,$(chromosomes),$(step3_dir)/$(chr).hdf5)
	touch $@

# $(step2_dir)/$(expr_matrix_filename).filtered.hdf5
#$(step3_dir)/step4.ok2start:
#	eqtl_settings.py $(step2_dir)/$(expr_matrix_filename).filtered.hdf5  $()<pheno.filtered.hdf5> $(corr_method) $(step3_dir)/$(corr_method)/$(corr_method).hdf5 $(kpop_file) <covariates.hdf5> 
#	touch $@
TARGETS5+=$(step3_dir)/complete $(foreach chr,$(chromosomes),$(step3_dir)/$(chr).hdf5)

phony_targets+= setup setup_files

###################################################
targets1:
	echo $(TARGETS1)
targets2:
	echo $(TARGETS2)
targets3:
	echo $(TARGETS3)
targets4:
	echo $(TARGETS4)
targets5:
	echo $(TARGETS5)


###################################################
# FORCE the program to run even if files haven't changed
FORCE:


#PHONY: performance improvement. Tell MAKE that those targets don't generate any files. 
.PHONY:  $(phony_targets)
.SILENT: $(silent_targets)

###################################################
