#!/usr/bin/env Rscript
#; -*- mode: R;-*-
#######################################################################
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with iRAP.  If not, see <http://www.gnu.org/licenses/>.
#######################################################################

args <- commandArgs(trailingOnly=TRUE)

if (length(args)!=3 && length(args)!=4 ) {
  print("Error: usage generate_pca expr.tsv sample2labels.tsv out_file [colors]")
  quit(status=1)
}

expr.file <- args[1]
map.file <- args[2]
out.file <- args[3]
col.map.file <- NULL
if ( length(args) == 4 ) {
  col.map.file <- args[4]
}
# TODO: validate files

#
expr.file
expr.df <- read.table(expr.file,header = T,check.names=F,sep='\t')
rownames(expr.df) <- expr.df[,1]

expr.df <- expr.df[,-1]
cat(dim(expr.df),"\n")

has.genes <- TRUE
if ( length(rownames(expr.df))==length(colnames(expr.df)) && sum(rownames(expr.df)== colnames(expr.df)) ==0 ) {
  has.genes <- FALSE
  cat("Squared matrix - assuming that rows/cols are samples.\n")
}

map.df <- read.table(map.file,header = F,check.names=F,sep='\t')
# 1st column=sample
# 2nd column=class/label
if ( sum(!colnames(expr.df) %in% as.character(map.df$V1))!=0 ) {
  cat("ERROR: some samples in expr matrix were not found in ",map.file,"\n")
  quit(status=1)
}
# subset the mapping
map.df <- map.df[map.df$V1 %in% colnames(expr.df),]

#
map.df.labels <- unique(as.character(map.df$V2))
#map.df.labels

# colors
if ( !is.null(col.map.file)) {
  nclass <- length(unique(map.df$V2))
  cat("Reading file with mapping between classes and colors from ",col.map.file,"...\n")
  col.df <- read.table(col.map.file,header = F,check.names=F,sep='\t',comment.char="")
  cat(dim(col.df),"\n")
  # 1st column=class/label
  # 2nd column=colour
  if ( nclass != nrow(col.df) ) {
    cat("ERROR: invalid number of classes in ",col.map.file,"\n")
    quit(status=1)
  }
  miss.class <- ! map.df.labels %in% as.character(col.df$V1)
  if ( sum(miss.class) > 0 ) {
    cat("ERROR: incomplete ",col.map.file,", missing ",sum(miss.class),"(e.g., ",map.df.labels[miss.class],")\n")
    quit(status=1)
  }
  class2colour <- as.character(col.df$V2)
  names(class2colour) <- as.character(col.df$V1)
  cat("Reading file with mapping between classes and colors...done.\n")
} else {
  if(!require(RColorBrewer)) {
    source("http://bioconductor.org/biocLite.R")
    biocLite("RColorBrewer",suppressUpdates=T)
  }
  suppressPackageStartupMessages(library(RColorBrewer))
  getPalette = colorRampPalette(brewer.pal(9, "Set1"))
  class2colour <- getPalette(length(map.df.labels))
  names(class2colour) <- map.df.labels
}
samples2colour <- as.character(map.df$V1)

rownames(map.df) <- map.df$V1
samples2colour <- as.character(class2colour[map.df[samples2colour,"V2"]])
names(samples2colour) <- as.character(map.df$V1)
samples2colour
if(!require(lattice)) {
  source("http://bioconductor.org/biocLite.R")
  biocLite("lattice",suppressUpdates=T)
}
suppressPackageStartupMessages(library("lattice"))

if ( has.genes) {
  # transpose the matrix so that samples are rows
  data <- t(expr.df)
} else {
  data <- as.matrix(data.frame(expr.df))
}
pca <- prcomp(data,center=TRUE,scale=TRUE)
pca.sum <- summary(pca)
print(pca)
print(pca.sum)
png(filename=out.file,width=1600,height=1600,res=150)
xyplot(PC1 ~ PC2,data=as.data.frame(pca$x),
            cex=2,
            col=samples2colour[rownames(pca$x)],
            pch=16,
       aspect=1,
            xlab=paste("PC2 (",round(pca.sum$importance["Proportion of Variance","PC2"],2)*100,"% of variance)",sep=""),
            ylab=paste("PC1 (",round(pca.sum$importance["Proportion of Variance","PC1"],2)*100,"% of variance)",sep=""),
            main = suppressWarnings(draw.key(key = list(
                                               rect = list(col = class2colour),
                                               text = list(names(class2colour)),
                                               columns=3
                                               ))))

dev.off()
png(filename=gsub(".png","_13.png",out.file),width=1600,height=1600,res=150)
xyplot(PC1 ~ PC3,data=as.data.frame(pca$x),
            cex=2,
            col=samples2colour[rownames(pca$x)],
            pch=16,
              aspect=1,
            xlab=paste("PC3 (",round(pca.sum$importance["Proportion of Variance","PC3"],2)*100,"% of variance)",sep=""),
            ylab=paste("PC1 (",round(pca.sum$importance["Proportion of Variance","PC1"],2)*100,"% of variance)",sep=""),
            main = suppressWarnings(draw.key(key = list(
                                               rect = list(col = class2colour),
                                               text = list(names(class2colour)),
                                               columns=3
                                               ))))

  
dev.off()

png(filename=gsub(".png","_23.png",out.file),width=1600,height=1600,res=150)
xyplot(PC2 ~ PC3,data=as.data.frame(pca$x),
            cex=2,
            col=samples2colour[rownames(pca$x)],
            pch=16,
              aspect=1,
            xlab=paste("PC3 (",round(pca.sum$importance["Proportion of Variance","PC3"],2)*100,"% of variance)",sep=""),
            ylab=paste("PC2 (",round(pca.sum$importance["Proportion of Variance","PC2"],2)*100,"% of variance)",sep=""),
            main = suppressWarnings(draw.key(key = list(
                                               rect = list(col = class2colour),
                                               text = list(names(class2colour)),
                                               columns=3
                                               ))))

  
dev.off()

q(status=0)
